### ISSUE TITLE
broken link on npm page

### ISSUE THREAD

**Issue by alfredbez** [akoenig/gulp-autocompletion-zsh#3]
The link on the [npm page](https://www.npmjs.com/package/gulp-autocompletion-zsh) (on the right side) is broken.

https://github.com/akoenig/gulp-completion-zsh should be https://github.com/akoenig/gulp-autocompletion-zsh (*autocompletion* instead of *completion*)

**Comment by akoenig** [comment]
Fixed it. Thanks for the heads up :)
